### ISSUE TITLE
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).

### ISSUE THREAD

**Issue by Zardoz89** [rianhunter/dbxfs#14]
When I launch dbxfs (~/.local/bin/dbxfs -c ~/.config/dbxfs/config.json) I a  warning/error. However dbxfs works and ask for my access token passphrase.

Console output :

    Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
    Traceback (most recent call last):
      File "/home/luis/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
        init_func = ep.load()
      File "/home/luis/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
        from . import file_base
      File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
        from keyring.util.escape import escape as escape_for_ini
    ModuleNotFoundError: No module named 'keyring.util.escape'
    Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
    Traceback (most recent call last):
      File "/home/luis/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
        init_func = ep.load()
      File "/home/luis/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
        from keyring.util.escape import escape as escape_for_ini
    ModuleNotFoundError: No module named 'keyring.util.escape'
    Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
    Traceback (most recent call last):
      File "/home/luis/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
        init_func = ep.load()
      File "/home/luis/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
        from keyring.util.escape import escape as escape_for_ini
    ModuleNotFoundError: No module named 'keyring.util.escape'

pip3 list | grep key : 

* keyring (15.1.0)
* keyrings.alt (3.0)

System : 

 * kUbunyu 18.04.1
 * python 3.6.6
 * pip3  9.0.1
 * dbxfs (1.0.31)

**Comment by Zardoz89** [comment]
It works. It should be added to the documentation.

**Comment by sunk818** [comment]
@rianhunter Can we have a wiki on this repo? This way, we can add/edit content. It is good to know procedures like this and a wiki may be a good way to contribute to the project without coding.

**Comment by rianhunter** [comment]
@sunk818 I've never liked wikis. They always get out of date and are usually bad at efficiently conveying information. Did you have a specific contribution in mind? Would you be open to contributing to a Jekyll site instead?

**Comment by Zardoz89** [comment]
Well.. a github wiki it's a jekyl site in disguise
