### ISSUE TITLE
Uncaught critical exception from FUSE operation getattr

### ISSUE THREAD

**Issue by JeffPsycle** [rianhunter/dbxfs#16]
Hi, pulled this out of my /var/log/messages this afternoon after the service crashed.

Running the following:

Fedora 28
Python 3.6.5
- dbxfs 1.0.34
- urllib3 1.24
- requests 2.20.0
- fusepyng 1.0.6
- dropbox 9.1.0

```
CRITICAL:fuse:Uncaught critical exception from FUSE operation getattr, aborting: '>' not supported between instances of 'NoneType' and 'int'.#012Traceback (most recent call last):#012

File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen#012
chunked=chunked)#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request#012
six.raise_from(e, None)#012  File "<string>", line 2, in raise_from#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request#012
httplib_response = conn.getresponse()#012  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse#012
response.begin()#012  File "/usr/lib64/python3.6/http/client.py", line 297, in begin#012
version, status, reason = self._read_status()#012  File "/usr/lib64/python3.6/http/client.py", line 266, in _read_status#012
raise RemoteDisconnected("Remote end closed connection without"#012http.client.RemoteDisconnected: Remote end closed connection without response#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012

File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send#012
timeout=timeout#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen#012
_stacktrace=sys.exc_info()[2])#012  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment#012
raise six.reraise(type(error), error, _stacktrace)#012  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise#012
raise value.with_traceback(tb)#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen#012
chunked=chunked)#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request#012
six.raise_from(e, None)#012  File "<string>", line 2, in raise_from#012  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request#012
httplib_response = conn.getresponse()#012  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse#012
response.begin()#012  File "/usr/lib64/python3.6/http/client.py", line 297, in begin#012
version, status, reason = self._read_status()#012  File "/usr/lib64/python3.6/http/client.py", line 266, in _read_status#012
raise RemoteDisconnected("Remote end closed connection without"#012urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012

File "/usr/local/lib/python3.6/site-packages/fusepyng.py", line 815, in _wrapper#012
return func(*args, **kwargs) or 0#012  File "/usr/local/lib/python3.6/site-packages/fusepyng.py", line 854, in getattr#012
return self.fgetattr(path, buf, None)#012  File "/usr/local/lib/python3.6/site-packages/fusepyng.py", line 1107, in fgetattr#012
attrs = self.operations('getattr', self._decode_optional_path(path), fh)#012  File "/usr/local/lib/python3.6/site-packages/fusepyng.py", line 1331, in __call__#012
ret = getattr(self, op)(path, *args)#012  File "/usr/local/lib/python3.6/site-packages/userspacefs/fuse_adapter.py", line 117, in getattr#012
st = self._fs.stat(self._conv_path(path))#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/translate_ignored_files.py", line 97, in stat#012
return self._sub.stat(self._convert_path(path))#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/cachingfs.py", line 1630, in stat#012
only_cache=only_cache)#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/cachingfs.py", line 1557, in _stat_repeat#012
new_stat = self._fs.x_stat_create(path, create_mode, directory)#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/dbxfs.py", line 679, in x_stat_create#012
return md_to_stat(self._stat_create(path, mode & ~os.O_TRUNC, directory))#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/dbxfs.py", line 639, in _stat_create#012
md = self._get_md_inner(path)#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/dbxfs.py", line 600, in _get_md_inner#012
md = self._clientv2.files_get_metadata(p)#012  File "/usr/local/lib/python3.6/site-packages/dropbox/base.py", line 1277, in files_get_metadata#012
None,#012

File "/usr/local/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request#012
timeout=timeout)#012

File "/usr/local/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry#012
timeout=timeout)#012

File "/usr/local/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string#012
timeout=timeout,#012  File "/usr/local/lib/python3.6/site-packages/dbxfs/dbxfs.py", line 553, in new_session_post#012
r = old_session_post(*n, **kw)#012  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 572, in post#012
return self.request('POST', url, data=data, json=json, **kwargs)#012

File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 524, in request#012
resp = self.send(prep, **send_kwargs)#012

File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 637, in send#012
r = adapter.send(request, **kwargs)#012

File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send#012
raise ConnectionError(err, request=request)#012requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012

File "/usr/local/lib/python3.6/site-packages/fusepyng.py", line 818, in _wrapper#012
if e.errno > 0:#012TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by rianhunter** [comment]
This was fixed in one of the dependencies a few days ago, but now I made it a required upgrade. Just upgrade dbxfs via 'pip3 install --upgrade dbxfs"
