### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by esturniolo** [rianhunter/dbxfs#27]
Hi.
I tried to install dbxfs in a VPS (OVH) and the installation via pip3 got some error dependencies...
A lot of:
`SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
After a little googling I found the packages that I should install to make the dbxfs works
`libpython-dev libpython2.7 libpython2.7-dev libssl-doc python2.7-dev zlib1g-dev`

I installed them (if you not have installed gcc and build-essential, you should install it too), uninstall dbxfs via pip3, install again with pip3 and...
_Successfully installed dbxfs-1.0.41_

But when I tried to run it....

```
$ dbxfs dropbox/
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/dbxfs", line 7, in <module>
    from dbxfs.main import main
  File "/usr/local/lib/python3.5/dist-packages/dbxfs/main.py", line 34, in <module>
    import dropbox
  File "/usr/local/lib/python3.5/dist-packages/dropbox/__init__.py", line 3, in <module>
    from .dropbox import __version__, Dropbox, DropboxTeam, create_session  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/dropbox/dropbox.py", line 17, in <module>
    import requests
  File "/usr/local/lib/python3.5/dist-packages/requests/__init__.py", line 105, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'

$ sudo -H pip3 install urllib3
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.13.1)

$ sudo -H pip3 install chardet
Requirement already satisfied: chardet in /usr/local/lib/python3.5/dist-packages (3.0.4)
```
I'm run out of options... Any clue?

Thanks!!!

**Comment by rianhunter** [comment]
Looks like your requests package is out of sync with your urllib3 package. I would try:

    sudo -H pip3 install --upgrade urllib3
    sudo -H pip3 install --upgrade requests

**Comment by esturniolo** [comment]
Works like a charm!

```
# pip3 install --upgrade urllib3
Collecting urllib3
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 879kB/s
Installing collected packages: urllib3
  Found existing installation: urllib3 1.13.1
    Uninstalling urllib3-1.13.1:
      Successfully uninstalled urllib3-1.13.1
Successfully installed urllib3-1.24.1

# pip3 install --upgrade requests
Requirement already up-to-date: requests in /usr/local/lib/python3.5/dist-packages (2.21.0)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests) (2.8)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests) (3.0.4)

$ dbxfs dropbox/
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=xxxxxxxxxxxxxxxxx
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authorization code (Ctrl-C to quit): xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
We're all connected. Do you want to save your credentials for future runs? [Y/n] y
Would you like to help us improve dbxfs by providing anonymous error reports? [Y/n] y
Do you want "dropbox/" to be the default mount point? [Y/n] y
```

Thanks for your help.

May be in the future you can add the dependencies in the readme to avoid some errors. I hat to install the following packages (OVH Ubuntu 16.04 image)
`libpython-dev libpython2.7 libpython2.7-dev libssl-doc python2.7-dev zlib1g-dev`

Happy new year!

**Comment by rianhunter** [comment]
Not entirely sure those packages were necessary, dbxfs relies on Python 3, not Python 2.7. In any case, there are countless ways for Python packaging to be broken or misconfigured unfortunately. Ideally dbxfs would be an official package for the most popular Linux distributions.

Happy you got it working, and happy new year to you as well.
