### ISSUE TITLE
/tmp is full after writing a number of large files

### ISSUE THREAD

**Issue by KrissN** [rianhunter/dbxfs#39]
I have made an attempt to use my Dropbox as backup storage for my laptop. My tool of choice for this job is ``borg``. During backup creation ``borg`` creates sequentially-numbered files, each up to 512MB (default settings).

When trying to make a backup using ``dbxfs`` to map my Dropbox account, the process works (albeit a bit slow), but the problem is that the ``/tmp`` directory starts filling up with ``tmpxxxx&cache=shared`` files, some of them being up to 512MB large. Eventually the quota is exhausted and the following error appears in ``dbxfs`` log:

```
2019-08-16 16:44:59,544:ERROR:fuse:Uncaught exception from FUSE operation write, returning errno.EINVAL: database or disk is full
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib64/python3.6/site-packages/fusepyng.py", line 947, in write
    offset, fh)
  File "/usr/lib64/python3.6/site-packages/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/lib64/python3.6/site-packages/userspacefs/fuse_adapter.py", line 143, in write
    return self._fs.pwrite(f, data, offset)
  File "/usr/lib64/python3.6/site-packages/dbxfs/cachingfs.py", line 1814, in pwrite
    return handle.pwrite(data, offset)
  File "/usr/lib64/python3.6/site-packages/dbxfs/cachingfs.py", line 1152, in pwrite
    return self._live_md.cached_file.pwrite(data, offset)
  File "/usr/lib64/python3.6/site-packages/dbxfs/cachingfs.py", line 1020, in pwrite
    return self._file.pwrite(data, offset)
  File "/usr/lib64/python3.6/site-packages/dbxfs/cachingfs.py", line 829, in pwrite
    return self._pwrite(cursor, data, offset)
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/lib64/python3.6/site-packages/dbxfs/cachingfs.py", line 198, in trans
    conn.commit()
sqlite3.OperationalError: database or disk is full
```

At the same time the backup process errors out with EINVAL.

I'm using latest ``dbxfs`` from git (60e206e).

**Comment by rianhunter** [comment]
git is unreleased, were you seeing this with the last release?

**Comment by KrissN** [comment]
Yes, I saw it also with 1.0.43. This is why I moved to git hoping that it was fixed in the meantime.

**Comment by rianhunter** [comment]
Thanks, I'll check it out when I can.

**Comment by KrissN** [comment]
I general I have the feeling that the write cache is somewhat disconnected from the read cache. When ˙˙borg˙˙ writes the index file (few hundered MBs) it first lands in ˙˙/tmp˙˙, from which it is uploaded to Dropbox. When upon next invocation ˙˙borg˙˙ reads the index file it is downloaded from Dropbox into the read cache, while a valid copy still resides in ˙˙/tmp˙˙, but is completely unused.

**Comment by rianhunter** [comment]
Yeah that shouldn't happen, so something is bugged. What you upload should be cached immediately and reused on a subsequent open.
