### ISSUE TITLE
Dbxfs hangs

### ISSUE THREAD

**Issue by gdistasi** [rianhunter/dbxfs#45]
It seems there are issue with the new ubuntu version (20.04).
Problems can be that programs hang when trying to access the dropbox directory.
Sometimes doing an ls in the parent directory shows the Dropbox directory as ??? ??? ??? Dropbox ?? ?? ??

To work out the issue you have to -9 kill dbxfs and try again. Sometimes even several attempts do not work out the issue.

**Comment by rianhunter** [comment]
If you're invested in getting this issue resolved I will gladly accept a PR and spend time reviewing it. I don't otherwise have time to resolve this myself but I can set aside my other responsibilities temporarily if you can donate $500 for an honest day's work. Thanks

**Comment by jnm** [comment]
Not trying to siphon Rian's time, but just in case it's useful for anyone's debugging efforts, I see a lot of this from `strace` when the hang happens:
```
[pid 180969] futex(0x934b70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 181022] futex(0x934b68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=141750, tv_nsec=691008702}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid 180967] futex(0x934b70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 180969] <... futex resumed>)       = 0
[pid 180967] <... futex resumed>)       = 0
[pid 180969] futex(0x934b68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=141750, tv_nsec=691035637}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid 180967] futex(0x934b68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=141750, tv_nsec=691117713}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid 181022] <... futex resumed>)       = -1 ETIMEDOUT (Connection timed out)
[pid 180969] <... futex resumed>)       = -1 ETIMEDOUT (Connection timed out)
[pid 180969] futex(0x934b70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 180967] <... futex resumed>)       = -1 ETIMEDOUT (Connection timed out)
[pid 181022] futex(0x934b70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
```

During the same hang:
```
(gdb) bt
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7ffc8d437760) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x7ffc8d437760, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f6f1dde44e8 in __new_sem_wait_slow (sem=0x7ffc8d437760, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007f6f1af10268 in fuse_session_loop_mt () from /lib/x86_64-linux-gnu/libfuse.so.2
#4  0x00007f6f1af15a4c in fuse_loop_mt () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007f6f1af187ad in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007f6f1cff1ff5 in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#7  0x00007f6f1cff140a in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#8  0x00007f6f1c75168c in _ctypes_callproc () from /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#9  0x00007f6f1c751bbc in ?? () from /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#10 0x00000000005f2406 in _PyObject_MakeTpCall ()
#11 0x000000000056c6a6 in _PyEval_EvalFrameDefault ()
#12 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#13 0x00000000005f1d85 in _PyFunction_Vectorcall ()
#14 0x00000000005984e7 in ?? ()
#15 0x00000000005a2dc3 in ?? ()
#16 0x00000000005f118e in PyObject_Call ()
#17 0x0000000000568e1f in _PyEval_EvalFrameDefault ()
#18 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#19 0x00000000005f1d85 in _PyFunction_Vectorcall ()
#20 0x00000000005f1107 in PyObject_Call ()
#21 0x0000000000568e1f in _PyEval_EvalFrameDefault ()
#22 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#23 0x00000000005f1d85 in _PyFunction_Vectorcall ()
#24 0x0000000000568819 in _PyEval_EvalFrameDefault ()
#25 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#26 0x00000000005f1d85 in _PyFunction_Vectorcall ()
#27 0x0000000000568819 in _PyEval_EvalFrameDefault ()
#28 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#29 0x00000000005f1d85 in _PyFunction_Vectorcall ()
#30 0x000000000056769f in _PyEval_EvalFrameDefault ()
#31 0x00000000006aa7a8 in ?? ()
#32 0x000000000056769f in _PyEval_EvalFrameDefault ()
#33 0x0000000000565972 in _PyEval_EvalCodeWithName ()
#34 0x0000000000686053 in PyEval_EvalCode ()
#35 0x00000000006753d1 in ?? ()
#36 0x000000000067544f in ?? ()
#37 0x0000000000675507 in PyRun_FileExFlags ()
#38 0x000000000067758a in PyRun_SimpleFileExFlags ()
#39 0x00000000006ae99e in Py_RunMain ()
#40 0x00000000006aed29 in Py_BytesMain ()
#41 0x00007f6f1de1b0b3 in __libc_start_main (main=0x4ebd20 <main>, argc=4, argv=0x7ffc8d439178, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc8d439168) at ../csu/libc-start.c:308
#42 0x00000000005f62ee in _start ()
(gdb) 
```

Perhaps the problem is in new FUSE code that was included with the latest Ubuntu LTS release. I also didn't see the problem until 20.04 (I was using 18.04 previously).

**Comment by rianhunter** [comment]
@jnm Could be a FUSE issue but could also be that dbxfs breaks some usage requirement in the newer version of FUSE. The dbxfs community would greatly appreciate it if you could dig further :)

**Comment by gdistasi** [comment]
It seems that the issue does not manifest itself when dbxfs is launched by root. Don't know why.

**Comment by rianhunter** [comment]
I've actually reproduced a hang and it's due to lack of a timeout on a dead socket.  It's likely the same hang. I will release a fix in the future but if someone wants this fixed ASAP here's the stack trace. Should be trivial to fix.

```
(gdb) info threads
  Id   Target Id                                   Frame
* 1    Thread 0x7f9164a7c740 (LWP 1158) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7fff0e3db000) at ../sysdeps/nptl/futex-internal.h:320
  2    Thread 0x7f915affd700 (LWP 1159) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x7f915affc920, clockid=1526712496, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  3    Thread 0x7f9160e12700 (LWP 1160) "dbxfs"    __lll_lock_wait (futex=futex@entry=0x7f914c003738, private=0) at lowlevellock.c:52
  4    Thread 0x7f915a7fc700 (LWP 1161) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x7f915a7f8650, clockid=1518306784, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  5    Thread 0x7f915b7fe700 (LWP 1162) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f914c00e650) at ../sysdeps/nptl/futex-internal.h:320
  6    Thread 0x7f915bfff700 (LWP 1163) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x7f915bffdf60, clockid=1543495408, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  7    Thread 0x7f9158ff9700 (LWP 1164) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f91440d5b20) at ../sysdeps/nptl/futex-internal.h:320
  8    Thread 0x7f9159ffb700 (LWP 1165) "dbxfs"    futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f9148001d20) at ../sysdeps/nptl/futex-internal.h:320
  9    Thread 0x7f913bfff700 (LWP 54962) "dbxfs"   futex_abstimed_wait_cancelable (private=0, abstime=0x7f913bffe920, clockid=1006626992, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  10   Thread 0x7f91597fa700 (LWP 2368029) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f91597f9830, clockid=1501534144, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  11   Thread 0x7f913b7fe700 (LWP 2828864) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f90f4004bd0) at ../sysdeps/nptl/futex-internal.h:320
  12   Thread 0x7f913affd700 (LWP 2828865) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f913affc920, clockid=989841584, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  13   Thread 0x7f9138ff9700 (LWP 2828909) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f9138ff6ef0, clockid=956264064, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  14   Thread 0x7f911affd700 (LWP 2862223) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f911affc830, clockid=452970432, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  15   Thread 0x7f911b7fe700 (LWP 2864738) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f911b7fd920, clockid=461363376, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  16   Thread 0x7f91197fa700 (LWP 3542296) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f9110000b60) at ../sysdeps/nptl/futex-internal.h:320
  17   Thread 0x7f9118ff9700 (LWP 3542299) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f9118ff6e30, clockid=419392960, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  18   Thread 0x7f90fbfff700 (LWP 3542300) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f9124001dc0) at ../sysdeps/nptl/futex-internal.h:320
  19   Thread 0x7f911bfff700 (LWP 3542322) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7f9128001030) at ../sysdeps/nptl/futex-internal.h:320
  20   Thread 0x7f9139ffb700 (LWP 3545945) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f9139ffa830, clockid=973055936, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  21   Thread 0x7f911a7fc700 (LWP 3545946) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f911a7fb920, clockid=444577968, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  22   Thread 0x7f913a7fc700 (LWP 1824915) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f913a7fb830, clockid=981448640, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  23   Thread 0x7f91397fa700 (LWP 2814059) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f91397f9830, clockid=964663232, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  24   Thread 0x7f9119ffb700 (LWP 2814064) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f9119ffa830, clockid=436185024, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  25   Thread 0x7f90fb7fe700 (LWP 2814069) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90fb7fd920, clockid=-75507536, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  26   Thread 0x7f90faffd700 (LWP 2814079) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90faffc920, clockid=-83900240, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  27   Thread 0x7f90fa7fc700 (LWP 2814080) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90fa7fb830, clockid=-92293184, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  28   Thread 0x7f90f9ffb700 (LWP 101697) "dbxfs"  futex_abstimed_wait_cancelable (private=0, abstime=0x7f90f9ffa830, clockid=-100685888, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  29   Thread 0x7f90f97fa700 (LWP 101701) "dbxfs"  futex_abstimed_wait_cancelable (private=0, abstime=0x7f90f97f9920, clockid=-109078352, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  30   Thread 0x7f90f8ff9700 (LWP 103584) "dbxfs"  futex_abstimed_wait_cancelable (private=0, abstime=0x7f90f8ff8920, clockid=-117471056, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  31   Thread 0x7f90dbfff700 (LWP 2001184) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90dbffe920, clockid=-603985744, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  32   Thread 0x7f90db7fe700 (LWP 2001273) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90db7fd920, clockid=-612378448, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  33   Thread 0x7f90daffd700 (LWP 2023197) "dbxfs" futex_abstimed_wait_cancelable (private=0, abstime=0x7f90daffc920, clockid=-620771152, expected=0, futex_word=0x8fe54c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
  34   Thread 0x7f90da7fc700 (LWP 2023271) "dbxfs" __libc_read (nbytes=135168, buf=0x7f90d0000ba0, fd=7) at ../sysdeps/unix/sysv/linux/read.c:26
(gdb) thread apply py-bt
Invalid thread ID: py-bt
(gdb) thread apply all py-bt

Thread 34 (Thread 0x7f90da7fc700 (LWP 2023271)):
Unable to locate python frame

Thread 33 (Thread 0x7f90daffd700 (LWP 2023197)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 32 (Thread 0x7f90db7fe700 (LWP 2001273)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 31 (Thread 0x7f90dbfff700 (LWP 2001184)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 30 (Thread 0x7f90f8ff9700 (LWP 103584)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 29 (Thread 0x7f90f97fa700 (LWP 101701)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 28 (Thread 0x7f90f9ffb700 (LWP 101697)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 27 (Thread 0x7f90fa7fc700 (LWP 2814080)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 26 (Thread 0x7f90faffd700 (LWP 2814079)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 25 (Thread 0x7f90fb7fe700 (LWP 2814069)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 24 (Thread 0x7f9119ffb700 (LWP 2814064)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 23 (Thread 0x7f91397fa700 (LWP 2814059)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 22 (Thread 0x7f913a7fc700 (LWP 1824915)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 21 (Thread 0x7f911a7fc700 (LWP 3545946)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 20 (Thread 0x7f9139ffb700 (LWP 3545945)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 19 (Thread 0x7f911bfff700 (LWP 3542322)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 922, in _upload_thread
    self._upload_cond.wait()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 18 (Thread 0x7f90fbfff700 (LWP 3542300)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 922, in _upload_thread
    self._upload_cond.wait()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 17 (Thread 0x7f9118ff9700 (LWP 3542299)):
Traceback (most recent call first):
  Waiting for the GIL
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1753, in recv_into
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
--Type <RET> for more, q to quit, c to continue without paging--
  File "/usr/lib/python3.8/http/client.py", line 1603, in getresponse
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "repos/dbxfs/dbxfs/dbxfs.py", line 163, in download_connection
    resp = conn.getresponse()
  File "repos/dbxfs/dbxfs/dbxfs.py", line 518, in readinto
    watch('reset')
  File "repos/dbxfs/dbxfs/cachingfs.py", line 408, in stream_file
    buf = fsource.read(DOWNLOAD_UNIT)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 16 (Thread 0x7f91197fa700 (LWP 3542296)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 569, in close
    self.thread.join()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 935, in close
    shutil.copyfileobj(self._upload_now, towrite)
  File "repos/dbxfs/dbxfs/cachingfs.py", line 920, in _upload_thread
    self._file.close()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 15 (Thread 0x7f911b7fe700 (LWP 2864738)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 14 (Thread 0x7f911affd700 (LWP 2862223)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 13 (Thread 0x7f9138ff9700 (LWP 2828909)):
Traceback (most recent call first):
  Waiting for the GIL
  File "repos/dbxfs/dbxfs/cachingfs.py", line 478, in _get_to_iter

  File "repos/dbxfs/dbxfs/cachingfs.py", line 279, in __init__
    res = self._get_to_iter(mutate, fs, path)
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1594, in open_directory
    return _Directory(self, path)
  File "repos/dbxfs/dbxfs/translate_ignored_files.py", line 97, in open_directory
    return _Directory(self._sub.open_directory(self._convert_path(path), *n, **kw))
  File "repos/dbxfs/dbxfs/safefs_glue.py", line 125, in open_directory
    return fs.open_directory(path)
  File "repos/userspacefs/userspacefs/fuse_adapter.py", line 168, in opendir
    return self._save_file(self._fs.open_directory(self._conv_path(path)))
  File "repos/fusepy/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "repos/fusepy/fusepyng.py", line 1289, in opendir

  File "repos/fusepy/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0

Thread 12 (Thread 0x7f913affd700 (LWP 2828865)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 11 (Thread 0x7f913b7fe700 (LWP 2828864)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1079, in close
    self._thread.join()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 2103, in open
  File "repos/dbxfs/dbxfs/translate_ignored_files.py", line 94, in open
    return self._sub.open(self._convert_path(path), *n, **kw)
  File "repos/dbxfs/dbxfs/safefs_glue.py", line 121, in open
    return WrappedFile(fs, fs.open(path, *n, **kw))
  File "repos/userspacefs/userspacefs/fuse_adapter.py", line 132, in open
    fi.fh = self._save_file(self._fs.open(self._conv_path(path), fi.flags))
  File "repos/fusepy/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "repos/fusepy/fusepyng.py", line 912, in open
    return self.operations('open', path.decode(self.encoding), fi)
  File "repos/fusepy/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0

Thread 10 (Thread 0x7f91597fa700 (LWP 2368029)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 9 (Thread 0x7f913bfff700 (LWP 54962)):
Traceback (most recent call first):
  Waiting for the GIL
--Type <RET> for more, q to quit, c to continue without paging--

Thread 8 (Thread 0x7f9159ffb700 (LWP 1165)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1267, in _refresh_thread_start
    to_refresh = self._refresh_queue.get()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 7 (Thread 0x7f9158ff9700 (LWP 1164)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1293, in _statvfs_caching_thread
    self._statvfs_event.wait()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 6 (Thread 0x7f915bfff700 (LWP 1163)):
Traceback (most recent call first):
  Waiting for the GIL
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1628, in _prune_thread
    # file doesn't exist
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 5 (Thread 0x7f915b7fe700 (LWP 1162)):
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "repos/dbxfs/dbxfs/cachingfs.py", line 1230, in conn_thread_start
    self._conn_thread_stop.wait()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 4 (Thread 0x7f915a7fc700 (LWP 1161)):
Traceback (most recent call first):
  Waiting for the GIL
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1753, in recv_into
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 1603, in getresponse
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 677, in _make_request
    chunked=chunked,
  File "repos/dbxfs/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1182, in urlopen
  File "repos/dbxfs/env/lib/python3.8/site-packages/requests/adapters.py", line 951, in send
  File "repos/dbxfs/env/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/requests/sessions.py", line 1298, in request
  File "repos/dbxfs/env/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "repos/dbxfs/dbxfs/dbxfs.py", line 557, in new_session_post
    r = old_session_post(*n, **kw)
  File "repos/dbxfs/env/lib/python3.8/site-packages/dropbox/dropbox.py", line 1071, in request_json_string
  File "repos/dbxfs/env/lib/python3.8/site-packages/dropbox/dropbox.py", line 719, in request_json_string_with_retry
    Get Dropbox client with modified headers
  File "repos/dbxfs/env/lib/python3.8/site-packages/dropbox/dropbox.py", line 1081, in request
  File "repos/dbxfs/env/lib/python3.8/site-packages/dropbox/base.py", line 2761, in files_list_folder_longpoll
    :class:`dropbox.files.PollError`
--Type <RET> for more, q to quit, c to continue without paging--
  File "repos/dbxfs/dbxfs/dbxfs.py", line 527, in delta_thread
    res = dbfs._clientv2.files_list_folder_longpoll(cursor)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "repos/dbxfs/env/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()

Thread 3 (Thread 0x7f9160e12700 (LWP 1160)):
Traceback (most recent call first):
  <built-in method _localdummy_destroyed of weakref object at remote 0x7f91605db540>

Thread 2 (Thread 0x7f915affd700 (LWP 1159)):
Traceback (most recent call first):
  Waiting for the GIL

Thread 1 (Thread 0x7f9164a7c740 (LWP 1158)):
Traceback (most recent call first):
  File "repos/fusepy/fusepyng.py", line 1293, in __init__
    def statfs(self, path):
  File "repos/userspacefs/userspacefs/fuse_adapter.py", line 1001, in run_fuse_mount
  File "repos/userspacefs/userspacefs/__init__.py", line 609, in mount_and_run_fs
  File "repos/userspacefs/userspacefs/__init__.py", line 586, in simple_main
  File "repos/dbxfs/dbxfs/main.py", line 3181, in _main
  File "repos/dbxfs/dbxfs/main.py", line 370, in main
    return _main(argv)
  File "bin/dbxfs", line 11, in <module>
    load_entry_point('dbxfs', 'console_scripts', 'dbxfs')()
(gdb)
```
