### ISSUE TITLE
Intermittent "Uncaught exception from FUSE operation write, returning errno.EINVAL: 0"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [rianhunter/dbxfs#49]
Message in journalctl shows:

```
Oct 05 08:47:15 my.host.name dbxfs[13298]: ERROR:fuse:Uncaught exception from FUSE operation write, returning errno.EINVAL: 0
                                                        Traceback (most recent call last):
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
                                                            return func(*args, **kwargs) or 0
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 947, in write
                                                            offset, fh)
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
                                                            ret = getattr(self, op)(path, *args)
                                                          File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 142, in write
                                                            f = self._fh_to_file[fh]
                                                        KeyError: 0
```

Command executed: `mv -v /path/outside/dbxfs/20200815_115216\(1\).jpg /path/inside/dbxfs/`
Result:
```
copied '/path/outside/dbxfs/20200815_115216\(1\).jpg' -> '/path/inside/dbxfs/20200815_115216(1).jpg'
mv: error writing '/path/inside/dbxfs/20200815_115216(1).jpg': Invalid argument
```

Happy to help with any diagnostics or debugging.

**Comment by rianhunter** [comment]
Is this reproducible every time you restart dbxfs?

**Comment by JonTheNiceGuy** [comment]
I can consistently cause the issue to occur, even having restarted dbxfs.

Context: I store family photos on Dropbox, and these photos are ones where I can't get the Dropbox client onto the device taking the photos, so I use Syncthing to sync them to this machine. I then have a script which indexes the photos transferred in, and places them into that person's path in the Dropbox file system. This has worked for several thousand files using dbxfs, and then has abruptly stopped.

The move operation creates a 0 byte file, with permissions 777, owned by root:root (the user running the script). The source file is owned by the service account running syncthing on this device (syncthing:nogroup), with permissions 644.

Dropbox has available storage space.

Further research: I unmounted dbxfs, remounted it, and then wrote "Hello World" to a file path in Dropbox. This worked fine. I removed that file, and then tried to copy in the image again, which resulted in the same FUSE error in syslog. Then writing "Hello World" to the same path I tried before returns the same error. 

The mount command returns this line for my dbxfs mount: `dbxfs on /media/.SOURCES/jon_dropbox type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions)`

Using `dbxfs -n` works for transferring the files, provided you mount the CIFS file system, like this: `mount -t cifs //127.0.0.1/dbxfs /media/.SOURCES/jon_dropbox/ -o user=guest,port=64285,guest,vers=1.0` (note that `dbxfs -s` doesn't mount the filesystem in Ubuntu 20.04 - I'll raise a separate issue about that one 😄).

**Comment by rianhunter** [comment]
If you can reliably reproduce this then you have found something worthwhile. What if you copy a small text file with the same source path as the source image to the location in dbxfs? Does that trigger it?

Can you post an strace of your mv command? Can you also post the dbxfs log from startup to when the bug is triggered. Make sure to enable DEBUG level logging. Don't do doing anything else except the bug repro to keep the log small and intelligible.

**Comment by JonTheNiceGuy** [comment]
My sincere apologies @rianhunter. I've been tied up with work and personal stuff since I filed this issue.

I have no idea on how to create an strace or how to enable DEBUG level logging. I'm happy to go looking for how to do it, unless you can give me some pointers. It may take (again) a few days to get the logging done for you again though, due to work/personal stuff getting in the way. ❤ for confirming this is helpful however! I'll get whatever done ASAP (normal life notwithstanding).

**Comment by rianhunter** [comment]
No pressure, take your time. never reply at all if you have more important things to do. I'm not paying you.

strace is just a normal linux command, get it through your package manager and run it like so "strace -ologfile.txt mv <source file> <target file>". To enable maximal dbxfs logging, use "-vv"

**Comment by JonTheNiceGuy** [comment]
So, I've finally had a chance to do "something".

Here's some details of the OS first:

```
root@debianqnap:~# uname -a
Linux debianqnap.north.sprig.gs 4.19.0-12-marvell #1 Debian 4.19.152-1 (2020-10-18) armv5tel GNU/Linux
root@debianqnap:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@debianqnap:~# pip3 freeze
appdirs==1.4.4
argon2-cffi==20.1.0
asn1crypto==0.24.0
block-tracing==1.0.1
certifi==2018.8.24
cffi==1.14.3
chardet==3.0.4
cryptography==2.6.1
dbxfs==1.0.43
dropbox==10.4.1
entrypoints==0.3
fusepyng==1.0.7
httplib2==0.11.3
idna==2.6
keyring==17.1.1
keyrings.alt==3.1.1
privy==6.0.0
pycparser==2.20
pycrypto==2.6.1
pycurl==7.43.0.2
PyGObject==3.30.4
PySimpleSOAP==1.16.2
python-apt==1.8.4.1
python-debian==0.1.35
python-debianbts==2.8.2
pyxattr==0.6.1
pyxdg==0.25
reportbug===7.5.3-deb10u1
requests==2.21.0
SecretStorage==2.3.1
sentry-sdk==0.18.0
six==1.12.0
ufw==0.36
urllib3==1.24.1
userspacefs==1.0.13
virtualenv==15.1.0
```

On to the debugging. I'd put a bundle of files into `/media/.SOURCES/jon_dropbox/Camera Upload/` and I was moving them, one by one, into `/media/.SOURCES/jon_dropbox/Our Shared Photos/YYYY/YYYY-MM/`. I split the screen using `tmux` and had the top window running `dbxfs` with the logging flags, using `tee` to pipe the logs into `~/dbxfs.log`, and in the bottom half, I'm running the `strace mv "$1" "$2" 2>&1 | tee /tmp/strace.$(basename "$1").log`

There's quite a few of these style messages in the `dbxfs -vv -f /media/.SOURCES/jon_dropbox 2>&1 | tee ~/dbxfs.log` output, during normal, working, operations:

```
2020-12-01 22:32:22,568:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/move HTTP/1.1" 200 None                                                     2020-12-01 22:32:22,660:DEBUG:fuse.log-mixin:<- rename None
2020-12-01 22:32:22,703:DEBUG:fuse.log-mixin:-> getattr / (None,)
2020-12-01 22:32:22,716:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861270.118392, 'st_ctime': 1606861270.118578, 'st_atime': 1606861270.118578, 'st_
size': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:22,727:DEBUG:fuse.log-mixin:-> getattr /Camera Uploads (None,)
2020-12-01 22:32:22,743:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861270.977805, 'st_ctime': 1606861270.977831, 'st_atime': 1606861270.977831, 'st_
size': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:22,766:DEBUG:fuse.log-mixin:-> getattr /Camera Uploads/2020-11-09 11.14.34.jpg (None,)
2020-12-01 22:32:22,789:DEBUG:dbxfs.dbxfs:GET Path/Camera Uploads/2020-11-09 11.14.34.jpg
2020-12-01 22:32:22,801:INFO:dropbox:Request to files/get_metadata
2020-12-01 22:32:22,854:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/users/get_space_usage HTTP/1.1" 200 None
2020-12-01 22:32:23,138:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/get_metadata HTTP/1.1" 200 None
2020-12-01 22:32:23,156:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1604920472.0, 'st_ctime': 1604958520.0, 'st_atime': 1604958520.0, 'st_size': 4487212,
 'st_mode': 33279, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,251:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos (None,)
2020-12-01 22:32:23,260:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861271.857133, 'st_ctime': 1606861271.85716, 'st_atime': 1606861271.85716, 'st_s$
ze': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,264:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020 (None,)
2020-12-01 22:32:23,274:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861272.188828, 'st_ctime': 1606861272.188856, 'st_atime': 1606861272.188856, 'st$
size': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,278:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020/2020-11 (None,)
2020-12-01 22:32:23,287:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861822.6765, 'st_ctime': 1606861822.676527, 'st_atime': 1606861822.676527, 'st_s$
ze': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,293:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg (None,)
2020-12-01 22:32:23,309:DEBUG:dbxfs.dbxfs:GET Path/Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg
2020-12-01 22:32:23,315:INFO:dropbox:Request to files/get_metadata
2020-12-01 22:32:23,582:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/get_metadata HTTP/1.1" 409 None
2020-12-01 22:32:23,622:DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
2020-12-01 22:32:23,638:DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 854, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1107, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 117, in getattr
    st = self._fs.stat(self._conv_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/translate_ignored_files.py", line 97, in stat
    return self._sub.stat(self._convert_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1695, in stat
    only_cache=only_cache)
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1677, in _stat_repeat
    raise OSError(errno.ENOENT, os.strerror(errno.ENOENT))
FileNotFoundError: [Errno 2] No such file or directory
2020-12-01 22:32:23,957:DEBUG:fuse.log-mixin:-> getattr / (None,)
2020-12-01 22:32:23,966:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861270.118392, 'st_ctime': 1606861270.118578, 'st_atime': 1606861270.118578, 'st$
size': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,970:DEBUG:fuse.log-mixin:-> getattr /Camera Uploads (None,)
2020-12-01 22:32:23,979:DEBUG:fuse.log-mixin:<- getattr {'st_birthtime': 0.0, 'st_mtime': 1606861270.977805, 'st_ctime': 1606861270.977831, 'st_atime': 1606861270.977831, 'st$
size': 0, 'st_mode': 16895, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0}
2020-12-01 22:32:23,985:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg (None,)
2020-12-01 22:32:23,993:DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
2020-12-01 22:32:23,997:DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 854, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1107, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 117, in getattr
    st = self._fs.stat(self._conv_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/translate_ignored_files.py", line 97, in stat
    return self._sub.stat(self._convert_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1695, in stat
    only_cache=only_cache)
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1677, in _stat_repeat
    raise OSError(errno.ENOENT, os.strerror(errno.ENOENT))
FileNotFoundError: [Errno 2] No such file or directory
2020-12-01 22:32:24,011:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg (None,)
2020-12-01 22:32:24,019:DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
2020-12-01 22:32:24,022:DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 854, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1107, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 117, in getattr
    st = self._fs.stat(self._conv_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/translate_ignored_files.py", line 97, in stat
    return self._sub.stat(self._convert_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1695, in stat
    only_cache=only_cache)
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1677, in _stat_repeat
    raise OSError(errno.ENOENT, os.strerror(errno.ENOENT))
FileNotFoundError: [Errno 2] No such file or directory
2020-12-01 22:32:24,035:DEBUG:fuse.log-mixin:-> getattr /Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg (None,)
2020-12-01 22:32:24,045:DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
2020-12-01 22:32:24,047:DEBUG:fuse:FUSE operation getattr raised a <class 'FileNotFoundError'>, returning errno 2.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 854, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1107, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 117, in getattr
    st = self._fs.stat(self._conv_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/translate_ignored_files.py", line 97, in stat
    return self._sub.stat(self._convert_path(path))
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1695, in stat
    only_cache=only_cache)
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1677, in _stat_repeat
    raise OSError(errno.ENOENT, os.strerror(errno.ENOENT))
FileNotFoundError: [Errno 2] No such file or directory
2020-12-01 22:32:24,060:DEBUG:fuse.log-mixin:-> rename /Camera Uploads/2020-11-09 11.14.34.jpg ('/Our Shared Photos/2020/2020-11/2020-11-09 11.14.34.jpg',)
2020-12-01 22:32:24,068:INFO:dropbox:Request to files/move
2020-12-01 22:32:25,037:DEBUG:urllib3.connectionpool:https://notify.dropboxapi.com:443 "POST /2/files/list_folder/longpoll HTTP/1.1" 200 17
2020-12-01 22:32:25,061:INFO:dropbox:Request to files/list_folder/continue
2020-12-01 22:32:25,399:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/list_folder/continue HTTP/1.1" 200 None
2020-12-01 22:32:25,417:INFO:dropbox:Request to users/get_space_usage
2020-12-01 22:32:25,435:INFO:dropbox:Request to files/list_folder/longpoll
```

However, I now can't get the bug to trip again (even moving the original failing file around).

At least I know what commands to run if it trips again. Is it worth closing this for now, or leaving it open, pending me getting it to trigger again?

Regards,

**Comment by rianhunter** [comment]
it's fine to leave it open, if you can't reproduce in a year or so i'll just close it
