### ISSUE TITLE
Intermittant "Uncaught exception from FUSE operation getattr, returning errno.EINVAL: no such table: md"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [rianhunter/dbxfs#50]
```
Oct 05 08:46:00 my.host.name dbxfs[15549]: ERROR:fuse:Uncaught exception from FUSE operation getattr, returning errno.EINVAL: no such table: md
                                                        Traceback (most recent call last):
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 815, in _wrapper
                                                            return func(*args, **kwargs) or 0
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 854, in getattr
                                                            return self.fgetattr(path, buf, None)
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1107, in fgetattr
                                                            attrs = self.operations('getattr', self._decode_optional_path(path), fh)
                                                          File "/usr/local/lib/python3.7/dist-packages/fusepyng.py", line 1331, in __call__
                                                            ret = getattr(self, op)(path, *args)
                                                          File "/usr/local/lib/python3.7/dist-packages/userspacefs/fuse_adapter.py", line 117, in getattr
                                                            st = self._fs.stat(self._conv_path(path))
                                                          File "/usr/local/lib/python3.7/dist-packages/dbxfs/translate_ignored_files.py", line 97, in stat
                                                            return self._sub.stat(self._convert_path(path))
                                                          File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1695, in stat
                                                            only_cache=only_cache)
                                                          File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1686, in _stat_repeat
                                                            return md.cached_file.stat()
                                                          File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 1001, in stat
                                                            st = self._file.stat()
                                                          File "/usr/local/lib/python3.7/dist-packages/dbxfs/cachingfs.py", line 642, in stat
                                                            cursor.execute("SELECT name, value FROM md WHERE name IN ('size', 'mtime', 'ctime')")
                                                        sqlite3.OperationalError: no such table: md
```

Discovered in /tmp the following files: `tmp1vlw_nqw` and `tmp1vlw_nqw&cache=shared`. The file `tmp1vlw_nqw` is empty, while `tmp1vlw_nqw&cache=shared` contains this content:

```
|WlCtablemdmdCREATE TABLE md
        ( name STRING PRIMARY KEY
        , value STRING NOT NULL
        )#7indexsqlite_autoindex_md_1mzOtableblocksblocksCREATE TABLE blocks
        ( blkidx INTEGER PRIMARY KEY
        , data BUFFER NOT NULL
        )
mtime_z&
        ctime_zsize
        mtime   ctime   size
```

dbxfs has been run, on this system, as root. There are several files in /tmp that are similar in construction:

```
root@my:/tmp# ls -l tmp*
-rw------- 1 root root     0 Oct  5 08:54  tmp1vlw_nqw
-rw-r--r-- 1 root root 16384 Oct  5 08:54 'tmp1vlw_nqw&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmp31szy_4m&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:53 'tmp3pmu2v1p&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:46 'tmp_5aocn46&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmp79olwwu4&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpapuszj_u&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:47 'tmpbcgg_vlh&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:46 'tmpe77pl6qv&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpercoh1im&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:46 'tmpes0d75_r&cache=shared'
-rw------- 1 root root     0 Oct  5 08:54  tmpgm73osem
-rw-r--r-- 1 root root 16384 Oct  5 08:54 'tmpgm73osem&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:47 'tmpgwdxg_k_&cache=shared'
-rw------- 1 root root     0 Oct  5 08:56  tmpjecp_rtn
-rw-r--r-- 1 root root 16384 Oct  5 08:56 'tmpjecp_rtn&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpnkp2vt23&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmppac4v9fz&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpq08iu7hr&cache=shared'
-rw-r--r-- 1 root root 16384 Oct  5 08:46 'tmpqi4oegvs&cache=shared'
-rw------- 1 root root     0 Oct  5 08:53  tmpsh1twcrd
-rw-r--r-- 1 root root 16384 Oct  5 08:53 'tmpsh1twcrd&cache=shared'
-rw------- 1 root root     0 Oct  5 08:53  tmptgz4yf1y
-rw-r--r-- 1 root root 16384 Oct  5 08:53 'tmptgz4yf1y&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpth37i76g&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:46 'tmptwml8clz&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:45 'tmpvsknbt0w&cache=shared'
-rw------- 1 root root     0 Oct  5 08:47  tmpvzomgr7o
-rw-r--r-- 1 root root 16384 Oct  5 08:47 'tmpvzomgr7o&cache=shared'
-rw-r--r-- 1 root root     0 Oct  5 08:46 'tmpwqqswrgy&cache=shared'
```

Happy to perform any diagnostics required!

**Comment by rianhunter** [comment]
The stray files in /tmp is a known issue. Those files are not related to the exception you are seeing. Not sure how your 'md' table is getting blown away. Seems like a sqlite bug. I imagine this error does not resurface immediately if you restart dbxfs. Does it always show up again eventually? If so, try upgrade sqlite on your system.

**Comment by JonTheNiceGuy** [comment]
I've not seen evidence of this occurring since that instance. I'm happy for it to be closed as I can't see how to replicate it.

**Comment by rianhunter** [comment]
Upgrade SQLite3 there is no possible code path in dbxfs that could result in the "md" table just disappearing.
