### ISSUE TITLE
Issues with CIFS flags in Ubuntu 20.04

### ISSUE THREAD

**Issue by JonTheNiceGuy** [rianhunter/dbxfs#51]
**Issue 1** - `dbxfs -s` does not mount.

I believe this is either that a fuse version of cifs-utils needs to be installed, that cifs.mount needs to be run as root (although, I've tested this and this doesn't work either), or that cifs.mount requires "different" options.
```
user@host:~$ dbxfs -vv -s temp
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=iftkeq2y4qj0nbt
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authorization code (Ctrl-C to quit): <REDACTED>
We're all connected. Do you want to save your credentials for future runs? [Y/n] n
Would you like to help us improve dbxfs by providing anonymous error reports? [Y/n] y
Do you want "temp" to be the default mount point? [Y/n] n
Unable to mount file system
```

**Issue 2** - `dbxfs -n` requires a path?

I'm not sure whether having a path is still a requirement, if you're not mounting the volume. If not, it should probably prompt you for a path.
```
user@host:~$ dbxfs -vv -n
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=iftkeq2y4qj0nbt
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authorization code (Ctrl-C to quit): <REDACTED>
We're all connected. Do you want to save your credentials for future runs? [Y/n] n
Do you want "None" to be the default mount point? [Y/n] n
Traceback (most recent call last):
  File "/usr/local/bin/dbxfs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/main.py", line 370, in main
    return _main(argv)
  File "/usr/local/lib/python3.7/dist-packages/dbxfs/main.py", line 357, in _main
    if not os.path.exists(mount_point):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Issue 3** dbxfs could provide more details on mounting cifs file systems 😄 
```
user@host:~$ dbxfs -n temp
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=iftkeq2y4qj0nbt
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authorization code (Ctrl-C to quit): <REDACTED>
We're all connected. Do you want to save your credentials for future runs? [Y/n] n
Do you want "temp" to be the default mount point? [Y/n] n
You can access the SMB server at cifs://guest:@127.0.0.1:63661/dbxfs
user@host:~$ sudo mount -t cifs //127.0.0.1/dbxfs temp -o user=guest,port=63661,guest
mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
user@host:~$ sudo tail -n 1 /var/log/messages
Oct  6 07:41:47 host kernel: [4408569.559863] No dialect specified on mount. Default has changed to a more secure dialect, SMB2.1 or later (e.g. SMB3), from CIFS (SMB1). To use the less secure SMB1 dialect to access old servers which do not support SMB3 (or SMB2.1) specify vers=1.0 on mount.
user@host:~$ sudo mount -t cifs //127.0.0.1/dbxfs temp -o user=guest,port=63661,guest,vers=1.0
```

It didn't seem worth raising these three separate, but related items as individual items. Happy to split them out if required.

I suspect the last one and first elements are probably linked.

**Comment by rianhunter** [comment]
issue 1 is normal on linux, the error message should be clearer.

issue 2 is fixed in d7af758

issue 3 is not really an issue since we don't tell the user how to mount the SMB share on their system, that is up to them.

so i'm marking this closed.
