### ISSUE TITLE
pkg_resources.DistributionNotFound on OpenBSD 6.8/amd64-stable

### ISSUE THREAD

**Issue by morgant** [rianhunter/dbxfs#59]
I'm running OpenBSD 6.8/amd64-stable and am trying to get `dbxfs` to work, but am getting the following error when I try to run `doas dbxfs -o uid=1000 ~/Dropbox`:

```
Traceback (most recent call last):
  File "/home/username/.local/bin/dbxfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dbxfs==1.0.50' distribution was not found and is required by the application
```

I installed as follows and added `~/.local/bin` to my `PATH`:

```
doas pkg_add py3-pip
pip3.8 install dbxfs
```

I can run `dbxfs -h` without error, but not `doas dbxfs -h`.

**Comment by rianhunter** [comment]
not sure, you probably need to run `doas pip3.8 install dbxfs`

**Comment by morgant** [comment]
@rianhunter Thanks, that worked.
