### ISSUE TITLE
Old SQLite version causes opaque error

### ISSUE THREAD

**Issue by dmd** [rianhunter/dbxfs#6]
Any ideas?

```
$ dbxfs dbx
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?client_id=my_client_id_here&response_type=code
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authoritization code (Ctrl-C to quit): entered my code here
We're all connected. Do you want to save your credentials for future runs? [Y/n] n
Would you like to help us improve dbxfs by providing anonymous error reports? [Y/n]
Do you want "dbx" to be the default mount point? [Y/n]

$ ls -ld dbx
ls: cannot access dbx: Bad address

$ ls -l|grep dbx
ls: cannot access dbx: Bad address
d?????????  ? ?        ?       ?            ? dbx

$ cd dbx
-bash: cd: dbx: Bad address
```

**Comment by rianhunter** [comment]
That's new. Seems like you enabled anonymous error reports but I'm not seeing any errors on my end.

Try this: In a separate terminal run "dbxfs -f -vv dbx" and then see what it spits out when you try to ls the dbx folder.

**Comment by dmd** [comment]
`Exception: Need sqlite version >= 3.9.0, you have: '3.7.17'`

**Comment by dmd** [comment]
or more fully,
```
2018-10-04 10:06:53,007:DEBUG:userspacefs:Attempting fuse mount
2018-10-04 10:06:53,015:DEBUG:fuse.log-mixin:-> init / ()
2018-10-04 10:06:53,017:INFO:dropbox:Request to files/list_folder/get_latest_cursor
2018-10-04 10:06:53,018:DEBUG:fuse.log-mixin:<- init '[Unhandled Exception]'
Traceback (most recent call last):
2018-10-04 10:06:53,021:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.dropboxapi.com
  File "/usr/lib/python3.4/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python3.4/site-packages/fuse.py", line 721, in init
    return self.operations('init', '/')
  File "/usr/lib/python3.4/site-packages/fuse.py", line 972, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/lib/python3.4/site-packages/userspacefs/fuse_adapter.py", line 96, in init
    self._fs = self._create_fs()
  File "/usr/lib/python3.4/site-packages/dbxfs/main.py", line 311, in create_fs
    fs = CachingFileSystem(DropboxFileSystem(access_token), cache_folder=cache_folder)
  File "/usr/lib/python3.4/site-packages/dbxfs/cachingfs.py", line 1080, in __init__
    raise Exception("Need sqlite version >= 3.9.0, you have: %r" % (sqlite3.sqlite_version,))
Exception: Need sqlite version >= 3.9.0, you have: '3.7.17'
2018-10-04 10:06:53,473:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/list_folder/get_latest_cursor HTTP/1.1" 200 None
2018-10-04 10:06:53,476:INFO:dropbox:Request to files/list_folder/continue
2018-10-04 10:06:53,830:DEBUG:urllib3.connectionpool:https://api.dropboxapi.com:443 "POST /2/files/list_folder/continue HTTP/1.1" 200 None
2018-10-04 10:06:53,833:INFO:dropbox:Request to files/list_folder/longpoll
2018-10-04 10:06:53,836:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): notify.dropboxapi.com
```

**Comment by rianhunter** [comment]
I see. I'll fix things to fail more gracefully and verbosely in that case but you can fix this now but upgrading your system's sqlite library.
